### ISSUE TITLE
Error: this app cannot be enabled because it makes the server unstable

### ISSUE THREAD

**Issue by easteregg** [shibby/owncloud-youtubedl#14]
Cannot install this app in Owncloud v9. 

the system also says: 

```
This app has no minimum ownCloud version assigned. This will be an error in ownCloud 11 and later.
```

**Comment by easteregg** [comment]
Ah! my bad, didn't see that it supports up to 8.1. Sorry. closing the issue.

**Comment by shibby** [comment]
Yeah, you didn't see because it doesn't write anywhere i guess :) Maybe someone writes this app at OC Hackathon :) 

https://owncloud.org/hackathon/
