### ISSUE TITLE
Only admin can download videos, owncloud

### ISSUE THREAD

**Issue by vimets** [shibby/owncloud-youtubedl#3]
Hi there, im on the latest version available of youtube-dl:
root@raspberrypi:# youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.03.1
[debug] Python version 2.7.3 - Linux-3.18.7-v7+-armv7l-with-debian-7.8
[debug] exe versions: avconv 9.14-6, avprobe 9.14-6
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

Only the admin user can download videos correctly, even audio, however the regular users get this error:
I've been googleing but can't find any solution.

Download Result:error
Download error
URL:https://www.youtube.com/watch?v=eicCbUS8GXs
Show Debug
Run Command: 
youtube-dl https://www.youtube.com/watch?v=eicCbUS8GXs -o "%(title)s.%(ext)s" --get-filename
Run Command: 
youtube-dl https://www.youtube.com/watch?v=eicCbUS8GXs -o "/media/owncloud/data/Jordi/files/Música/Foyone--El-Cordero-de-Dios.mp4"
/usr/local/bin/youtube-dl/youtube_dl/options.py:788: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/usr/local/bin/youtube-dl/__main__.py", line 19, in File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 403, in main File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 195, in _real_main UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 34: ordinal not in range(128) 

Thanks in advanced!

**Comment by shibby** [comment]
Did you install youtube-dl with package manager?
I didnt get understand that why did you get this error.

**Comment by vimets** [comment]
Thanks for the quick reply, I've followed the README steps from the package that sends me to this other webpage --> http://rg3.github.io/youtube-dl/download.html for installing it. and then -->

sudo curl https://yt-dl.org/downloads/2015.03.03.1/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+x /usr/local/bin/youtube-dl

seems everything Ok, with the user that administrates de owncloud everything is working fine, mp3 and video files can be downloaded correctly, very useful, so the others users want this feature too.
Thanks for the app and for your time, if you come up with some solution make me know it, i will do the same if i can solve it somehow.

**Comment by vimets** [comment]
Hi there again!
I've figured out that the problem was that the save path contanied an accent, i'm a catalan speaker that is a language close to spanish that contains a lot of accents too, and Music is translated as Música.
So after removing the accent to the Música folder, renamed to just Musica, started to work!
Thanks for your time, didn't thought to test this before posting.
Hope it can help you for future updates!

**Comment by shibby** [comment]
Thank you for your contribition. This problem seems about youtube-dl. 

/usr/local/bin/youtube-dl/youtube_dl/options.py:788: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode 

For youtube-dl, all folder names must be unicoded.
